import { ProfileItem, ProxyItem } from './types';

export const APP_NAME = "Accsafe";

export const SOCIAL_LINKS = [
  { name: 'Facebook', url: 'https://facebook.com', color: 'bg-blue-600', icon: 'FB' },
  { name: 'Zalo', url: 'https://zalo.me', color: 'bg-blue-500', icon: 'Zalo' },
  { name: 'Telegram', url: 'https://telegram.org', color: 'bg-sky-500', icon: 'TG' },
  { name: 'Instagram', url: 'https://instagram.com', color: 'bg-pink-600', icon: 'IG' }
];

export const AUTOMATION_SCRIPTS = [
  { id: 'fb-login', name: 'Facebook Login', url: 'https://facebook.com', icon: 'Facebook' },
  { id: 'amz-surf', name: 'Amazon Surfing', url: 'https://amazon.com', icon: 'ShoppingBag' },
  { id: 'google-farm', name: 'Google Farming', url: 'https://google.com', icon: 'Chrome' },
  { id: 'yt-watch', name: 'YouTube Watch', url: 'https://youtube.com', icon: 'Youtube' },
];

export const CPU_OPTIONS = [2, 4, 8, 16, 32];
export const RAM_OPTIONS = [4, 8, 16, 32, 64];
export const RESOLUTION_OPTIONS = [
  "1920x1080",
  "1366x768",
  "1440x900",
  "2560x1440",
  "2560x1600",
  "3840x2160"
];

export const TRANSLATIONS = {
  en: {
    login: "Login",
    register: "Register",
    logout: "Logout",
    dashboard: "Dashboard",
    profiles: "Profiles",
    proxies: "Proxies",
    automation: "Automation",
    support: "Support",
    settings: "Settings",
    createProfile: "Create Profile",
    addProxy: "Add Proxy",
    open: "Open",
    stop: "Stop",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirmLogout: "Are you sure you want to logout?",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    orLoginWith: "Or login with",
    profileName: "Profile Name",
    deviceType: "Device Type",
    proxy: "Proxy",
    hardware: "Hardware",
    advanced: "Advanced",
    overview: "Overview",
    browser: "Browser",
    os: "Operating System",
    userAgent: "User Agent",
    generate: "Generate",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark Mode",
    changePassword: "Change Password",
    oldPassword: "Old Password",
    newPassword: "New Password",
    contact: "Contact Channels",
    docs: "Documentation",
    noProfiles: "No profiles found. Create one to get started.",
    noProxies: "No proxies found.",
    running: "Running",
    stopped: "Stopped",
    success: "Success",
    error: "Error",
    savedSuccessfully: "Saved successfully!",
    deletedSuccessfully: "Deleted successfully!",
    passwordChanged: "Password changed successfully!",
    passwordMismatch: "Old password is incorrect!",
    confirmDelete: "Are you sure you want to delete this?",
    supportChat: "Chat with us",
    cpuCores: "CPU Cores",
    memory: "Memory (RAM)",
    screenRes: "Screen Resolution",
    gpu: "Graphics Card (GPU Masking)",
    canvasNoise: "Canvas Noise",
    audioNoise: "AudioContext Noise",
    webrtc: "WebRTC Policy",
    advancedWarn: "Advanced Fingerprinting",
    advancedWarnDesc: "Changing these settings may affect browser stability or detectability.",
    adminPanel: "Admin Panel",
    typeMessage: "Type a message...",
    send: "Send",
    noChats: "No active conversations.",
    chatHistory: "Chat History",
    clearChat: "Clear Chat",
    clearChatConfirm: "Are you sure you want to clear this conversation history?",
    admin: "Administrator"
  },
  vi: {
    login: "Đăng nhập",
    register: "Đăng ký",
    logout: "Đăng xuất",
    dashboard: "Tổng quan",
    profiles: "Quản lý Hồ sơ",
    proxies: "Quản lý Proxy",
    automation: "Tự động hóa",
    support: "Hỗ trợ",
    settings: "Cài đặt",
    createProfile: "Tạo Hồ sơ",
    addProxy: "Thêm Proxy",
    open: "Mở",
    stop: "Dừng",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    cancel: "Hủy",
    confirmLogout: "Bạn có chắc chắn muốn đăng xuất?",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    orLoginWith: "Hoặc đăng nhập với",
    profileName: "Tên hồ sơ",
    deviceType: "Loại thiết bị",
    proxy: "Máy chủ Proxy",
    hardware: "Phần cứng",
    advanced: "Nâng cao",
    overview: "Tổng quan",
    browser: "Trình duyệt",
    os: "Hệ điều hành",
    userAgent: "User Agent",
    generate: "Tạo ngẫu nhiên",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    darkMode: "Chế độ tối",
    changePassword: "Đổi mật khẩu",
    oldPassword: "Mật khẩu cũ",
    newPassword: "Mật khẩu mới",
    contact: "Kênh hỗ trợ",
    docs: "Tài liệu hướng dẫn",
    noProfiles: "Chưa có hồ sơ nào. Hãy tạo mới.",
    noProxies: "Chưa có proxy nào.",
    running: "Đang chạy",
    stopped: "Đã dừng",
    success: "Thành công",
    error: "Lỗi",
    savedSuccessfully: "Đã lưu thành công!",
    deletedSuccessfully: "Đã xóa thành công!",
    passwordChanged: "Đổi mật khẩu thành công!",
    passwordMismatch: "Mật khẩu cũ không đúng!",
    confirmDelete: "Bạn có chắc chắn muốn xóa mục này không?",
    supportChat: "Chat với chúng tôi",
    cpuCores: "Số nhân CPU",
    memory: "Bộ nhớ (RAM)",
    screenRes: "Độ phân giải màn hình",
    gpu: "Card đồ họa (GPU)",
    canvasNoise: "Nhiễu Canvas",
    audioNoise: "Nhiễu Âm thanh (AudioContext)",
    webrtc: "Chính sách WebRTC",
    advancedWarn: "Cấu hình vân tay nâng cao",
    advancedWarnDesc: "Thay đổi các cài đặt này có thể ảnh hưởng đến độ ổn định của trình duyệt hoặc khả năng bị phát hiện.",
    adminPanel: "Trang Quản Trị",
    typeMessage: "Nhập tin nhắn...",
    send: "Gửi",
    noChats: "Không có cuộc trò chuyện nào.",
    chatHistory: "Lịch sử Chat",
    clearChat: "Làm mới cuộc trò chuyện",
    clearChatConfirm: "Bạn có chắc chắn muốn xóa toàn bộ lịch sử trò chuyện này không?",
    admin: "Quản trị viên"
  }
};

export const MOCK_USER_AGENTS = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
];

export const MOCK_GPUS = [
  "NVIDIA GeForce RTX 3060",
  "NVIDIA GeForce RTX 4090",
  "AMD Radeon RX 6700 XT",
  "Intel Iris Xe Graphics",
  "Apple M1",
  "Apple M2 Pro"
];